---
# Add sudo users
- name: 添加日常管理用户.
  hosts: init
  gather_facts: false
  tasks:
    - name: Add sudo user
      user:
        name: "{{ ops_add_user }}"
        password: "{{ ops_add_user_password | password_hash('sha512') }}"
        state: present
        groups: wheel
